### PR TITLE
Laravel 9 

### PR DESCRIPTION
**Pull request by bryanrscott**
Primarily done with Laravel Shift (https://laravelshift.com/), which was awesome on doing this update.
Only some minor hand edits in the final commit.

Laravel 9 requires PHP 8.   This is why the tests are failing at the moment, the dockerimage is php 7

The livewire-table for users and roles could be improved.

### CODE REVIEW

**Review by coderkoala — COMMENTED** [review]
Hi there Bryan, awesome work. I see no changes pertaining to vite here. Will we persist with webpack for now, or is it planned by @rappasoft in the coming days?

I've personally grown fond of vite, and it'd make spinning assets easier imo.

**Comment by bryanrscott** [comment]
@coderkoala I would see vite as a seperate pull request.  
Always happy for any help.

**Comment by victoriusnet** [comment]
Hi,

I have pulled this from https://github.com/bryanrscott/laravel-boilerplate, will this pull request be merged?

Can I use it? 

Thanks!

**Comment by ccsliinc** [comment]
I have submitted another PR, this is complete with testing and Vite

**Pull request closed without merging**
