### PR TITLE
Missing name attribute added to UserTable

### PR DESCRIPTION
**Pull request by mkysoft**
name attribute not showed because of missing attribute parameter.

### CODE REVIEW

**Comment by dregad** [comment]
@mkysoft thanks, I confirm this fixes the problem. 

The same fix should be applied to the `Type` column too, as well as in the RolesTable class for both columns.

**Comment by rappasoft** [comment]
What issue is this causing you? This is not needed, it is inferred: https://github.com/rappasoft/laravel-livewire-tables/blob/master/src/Views/Column.php#L79

**Comment by mkysoft** [comment]
> What issue is this causing you? This is not needed, it is inferred: https://github.com/rappasoft/laravel-livewire-tables/blob/master/src/Views/Column.php#L79

You are right now, code use label as field name. When I created this pull request firt time, Name field not displaying on User table. I made this changes because of @dregad comment.

**Comment by dregad** [comment]
> What issue is this causing you? This is not needed, it is inferred: https://github.com/rappasoft/laravel-livewire-tables/blob/master/src/Views/Column.php#L79

@rappasoft I did not re-test this against the latest development branch, but the problem is that you're passing the column's *label* to the constructor, so the logic only works as long as the lowercase label matches the column's name, which is often not the case in localized settings. See #1457 for details.

**Comment by rappasoft** [comment]
Ah ok I understand now.

**Comment by rappasoft** [comment]
Adding this manually because the massive refactor I did makes it easier that way right now. Thanks for finding the issue though!

**Pull request closed without merging**
