### PR TITLE
Fixed mistranslation of Chinese

### PR DESCRIPTION
**Pull request by skys215**

### CODE REVIEW

**Comment by rappasoft** [comment]
Bump

**Comment by skys215** [comment]
Do I need to take action for merge?

**Comment by rappasoft** [comment]
No sorry I just haven't been able to get to this project for a while. I'll try to get to all of it this week.

**Comment by skys215** [comment]
I got it, thanks for your time.😄

**Comment by rappasoft** [comment]
Bump

**Pull request merged**
